
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_BIN="$HOME/.bun/bin"
          export PATH="$BUN_BIN:$PATH"
          echo "$BUN_BIN" >> $GITHUB_PATH

      - name: Install Dependencies
        run: bun install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun run semantic-release
